# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e4dfabe63db43c1f1cd436bb7af57069"
name = "Abandoned Checkout App"
handle = "abandoned-checkout-app-3"
application_url = "https://solo-tunnel-zero-linking.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-f589edcd.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products"

[auth]
redirect_urls = [
  "https://solo-tunnel-zero-linking.trycloudflare.com/auth/callback",
  "https://solo-tunnel-zero-linking.trycloudflare.com/auth/shopify/callback",
  "https://solo-tunnel-zero-linking.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "https://rides-granted-subtle-antarctica.trycloudflare.com/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://rides-granted-subtle-antarctica.trycloudflare.com/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://rides-granted-subtle-antarctica.trycloudflare.com/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://rides-granted-subtle-antarctica.trycloudflare.com/webhooks/app/uninstalled"

[pos]
embedded = false
