# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "66e7df7cac5412f3a99a62879dfe3e04"
name = "sp-recovery-monkey\r\r\r\r\r"
handle = "sp-recovery-monkey"
application_url = "https://trip-standards-desirable-usc.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-f589edcd.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://trip-standards-desirable-usc.trycloudflare.com/auth/callback",
  "https://trip-standards-desirable-usc.trycloudflare.com/auth/shopify/callback",
  "https://trip-standards-desirable-usc.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
topics = ["checkouts/update"] 
uri = "/webhooks/checkouts" 

[pos]
embedded = false
